=== nluttenberger/Ingredients/igt-catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://fruschtique.de/ns/igt-catalog" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fc="http://fruschtique.de/ns/igt-catalog" xmlns:xi="http://www.w3.org/2001/XInclude">

    <xs:simpleType name="classIDType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="alc"/>
            <xs:enumeration value="carb"/>
            <xs:enumeration value="egg"/>
            <xs:enumeration value="fat"/>
            <xs:enumeration value="fish"/>
            <xs:enumeration value="fruit"/>
            <xs:enumeration value="herb"/>
            <xs:enumeration value="meat"/>
            <xs:enumeration value="milk"/>
            <xs:enumeration value="nuts"/>
            <xs:enumeration value="onion"/>
            <xs:enumeration value="condi"/>
            <xs:enumeration value="veg"/>
            <xs:enumeration value="spice"/>
            <xs:enumeration value="sweet"/>
            <xs:enumeration value="etc"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="classType">
        <xs:sequence>
            <xs:element name="classLabel" type="xs:string" minOccurs="0"/>
            <xs:element name="classColor" type="xs:string"/>
            <xs:element name="classColorHex" type="xs:hexBinary"/>
            <xs:element name="classColorRGBa" type="xs:string"/>
            <xs:element name="R" type="xs:nonNegativeInteger"/>
            <xs:element name="G" type="xs:nonNegativeInteger"/>
            <xs:element name="B" type="xs:nonNegativeInteger"/>
            <xs:element name="a" type="xs:decimal"/>
        </xs:sequence>
        <xs:attribute name="classID" type="fc:classIDType" use="required"/>
    </xs:complexType>

    <xs:complexType name="classesType">
        <xs:sequence>
            <xs:element name="class" type="fc:classType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ingredientType">
        <xs:sequence>
            <xs:element name="igtLabel" type="xs:string"/>
            <xs:element name="igtSyn" minOccurs="0" type="xs:string" maxOccurs="unbounded"></xs:element>
            <xs:element name="igtClass" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="repl" type="xs:IDREF" use="optional"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="ingredientsType">
        <xs:sequence>
            <xs:element name="ingredient" type="fc:ingredientType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="igtCatalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="classes" type="fc:classesType" minOccurs="0"/>
                <xs:element name="ingredients" type="fc:ingredientsType"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="classKey">
            <xs:selector xpath="fc:classes/fc:class"/>
            <xs:field xpath="@classID"/>
        </xs:key>
        <xs:keyref refer="fc:classKey" name="classRef">
            <xs:selector xpath="fc:ingredients/fc:ingredient"/>
            <xs:field xpath="fc:igtClass"/>
        </xs:keyref>
    </xs:element>

</xs:schema>

=== nluttenberger/Ingredients/igt-catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<fc:igtCatalog xmlns:fc="http://fruschtique.de/ns/igt-catalog"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://fruschtique.de/ns/igt-catalog igt-catalog.xsd">
   <fc:classes>
      <fc:class classID="alc">
         <fc:classLabel>Alkohol</fc:classLabel>
         <fc:classColor>AliceBlue</fc:classColor>
         <fc:classColorHex>F0F8FF</fc:classColorHex>
         <fc:classColorRGBa>rgba( 38,131,131,1)</fc:classColorRGBa>
         <fc:R>240</fc:R>
         <fc:G>248</fc:G>
         <fc:B>255</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="carb">
         <fc:classLabel>Kohlenhydrate</fc:classLabel>
         <fc:classColor>BurlyWood</fc:classColor>
         <fc:classColorHex>DEB887</fc:classColorHex>
         <fc:classColorRGBa>rgba( 17,113,113,1)</fc:classColorRGBa>
         <fc:R>222</fc:R>
         <fc:G>184</fc:G>
         <fc:B>135</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="condi">
         <fc:classLabel>Zubereitung</fc:classLabel>
         <fc:classColor>CadetBlue</fc:classColor>
         <fc:classColorHex>5F9EA0</fc:classColorHex>
         <fc:classColorRGBa>rgba(  5, 93, 93,1)</fc:classColorRGBa>
         <fc:R>95</fc:R>
         <fc:G>158</fc:G>
         <fc:B>160</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="egg">
         <fc:classLabel>Ei</fc:classLabel>
         <fc:classColor>Orange</fc:classColor>
         <fc:classColorHex>FFA500</fc:classColorHex>
         <fc:classColorRGBa>rgba( 86,197, 86,1)</fc:classColorRGBa>
         <fc:R>255</fc:R>
         <fc:G>165</fc:G>
         <fc:B>0</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="etc">
         <fc:classLabel>etc</fc:classLabel>
         <fc:classColor>WhiteSmoke</fc:classColor>
         <fc:classColorHex>F5F5F5</fc:classColorHex>
         <fc:classColorRGBa>rgba(  7,124,  7,1)</fc:classColorRGBa>
         <fc:R>245</fc:R>
         <fc:G>245</fc:G>
         <fc:B>245</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="fat">
         <fc:classLabel>Fett</fc:classLabel>
         <fc:classColor>Bisque</fc:classColor>
         <fc:classColorHex>FFE4C4</fc:classColorHex>
         <fc:classColorRGBa>( 50,174, 50,1)</fc:classColorRGBa>
         <fc:R>255</fc:R>
         <fc:G>228</fc:G>
         <fc:B>196</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="fish">
         <fc:classLabel>Fisch</fc:classLabel>
         <fc:classColor>Pink</fc:classColor>
         <fc:classColorHex>FFC0CB</fc:classColorHex>
         <fc:classColorRGBa>rgba(247,108,108,1)</fc:classColorRGBa>
         <fc:R>255</fc:R>
         <fc:G>192</fc:G>
         <fc:B>203</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="fruit">
         <fc:classLabel>Frucht</fc:classLabel>
         <fc:classColor>OliveDrab</fc:classColor>
         <fc:classColorHex>6B8E23</fc:classColorHex>
         <fc:classColorRGBa>rgba(247,171,108,1)</fc:classColorRGBa>
         <fc:R>107</fc:R>
         <fc:G>142</fc:G>
         <fc:B>35</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="herb">
         <fc:classLabel>Kräuter</fc:classLabel>
         <fc:classColor>GoldenRod</fc:classColor>
         <fc:classColorHex>DAA520</fc:classColorHex>
         <fc:classColorRGBa>rgba(155,  8,  8,1)</fc:classColorRGBa>
         <fc:R>218</fc:R>
         <fc:G>165</fc:G>
         <fc:B>32</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="meat">
         <fc:classLabel>Fleisch</fc:classLabel>
         <fc:classColor>IndianRed</fc:classColor>
         <fc:classColorHex>CD5C5C</fc:classColorHex>
         <fc:classColorRGBa>rgba(188, 29, 29,1)</fc:classColorRGBa>
         <fc:R>205</fc:R>
         <fc:G>92</fc:G>
         <fc:B>92</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="milk">
         <fc:classLabel>Milch</fc:classLabel>
         <fc:classColor>Lavender</fc:classColor>
         <fc:classColorHex>E6E6FA</fc:classColorHex>
         <fc:classColorRGBa>rgba( 23,151, 23,1)</fc:classColorRGBa>
         <fc:R>230</fc:R>
         <fc:G>230</fc:G>
         <fc:B>250</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="nuts">
         <fc:classLabel>Nüsse</fc:classLabel>
         <fc:classColor>Chocolate</fc:classColor>
         <fc:classColorHex>D2691E</fc:classColorHex>
         <fc:classColorRGBa>rgba(155, 75,  8,1)</fc:classColorRGBa>
         <fc:R>210</fc:R>
         <fc:G>105</fc:G>
         <fc:B>30</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="onion">
         <fc:classLabel>Zwiebel</fc:classLabel>
         <fc:classColor>Gold</fc:classColor>
         <fc:classColorHex>FFD700</fc:classColorHex>
         <fc:classColorRGBa>rgba(218,133, 63,1)</fc:classColorRGBa>
         <fc:R>255</fc:R>
         <fc:G>215</fc:G>
         <fc:B>0</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="spice">
         <fc:classLabel>Gewürz</fc:classLabel>
         <fc:classColor>Tomato</fc:classColor>
         <fc:classColorHex>FF6347</fc:classColorHex>
         <fc:classColorRGBa>rgba( 255,99,71,1)</fc:classColorRGBa>
         <fc:R>255</fc:R>
         <fc:G>99</fc:G>
         <fc:B>71</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="sweet">
         <fc:classLabel>süß</fc:classLabel>
         <fc:classColor>Salmon</fc:classColor>
         <fc:classColorHex>FA8072</fc:classColorHex>
         <fc:classColorRGBa>rgba( 65,148,148,1)</fc:classColorRGBa>
         <fc:R>250</fc:R>
         <fc:G>128</fc:G>
         <fc:B>114</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
      <fc:class classID="veg">
         <fc:classLabel>Gemüse</fc:classLabel>
         <fc:classColor>YellowGreen</fc:classColor>
         <fc:classColorHex>9ACD32</fc:classColorHex>
         <fc:classColorRGBa>rgba(188,101, 29,1)</fc:classColorRGBa>
         <fc:R>154</fc:R>
         <fc:G>205</fc:G>
         <fc:B>50</fc:B>
         <fc:a>1</fc:a>
      </fc:class>
   </fc:classes>
   <fc:ingredients>
      <fc:ingredient id="">
         <fc:igtLabel/>
         <fc:igtSyn>salz, pfeffer</fc:igtSyn>
         <fc:igtSyn>salz und pfeffer</fc:igtSyn>
         <fc:igtSyn>pfeffer und salz</fc:igtSyn>
         <fc:igtClass>spice</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="">
         <fc:igtLabel/>
         <fc:igtSyn>salz</fc:igtSyn>
         <fc:igtSyn>kala namak</fc:igtSyn>
         <fc:igtSyn>meersalz</fc:igtSyn>
         <fc:igtClass>spice</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="">
         <fc:igtLabel/>
         <fc:igtSyn>wasser</fc:igtSyn>
         <fc:igtSyn>mineralwasser</fc:igtSyn>
         <fc:igtSyn>salzwasser</fc:igtSyn>
         <fc:igtSyn>eiswasser</fc:igtSyn>
         <fc:igtSyn>eis</fc:igtSyn>
         <fc:igtClass>etc</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="">
         <fc:igtLabel/>
         <fc:igtSyn>öl</fc:igtSyn>
         <fc:igtClass>fat</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="">
         <fc:igtLabel/>
         <fc:igtSyn>natron</fc:igtSyn>
         <fc:igtClass>condi</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="">
         <fc:igtLabel/>
         <fc:igtSyn>fett</fc:igtSyn>
         <fc:igtClass>fat</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="">
         <fc:igtLabel>Pfeffer</fc:igtLabel>
         <fc:igtClass>spice</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="aal">
         <fc:igtLabel>Aal</fc:igtLabel>
         <fc:igtClass>fish</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ackerbohne">
         <fc:igtLabel>Ackerbohne</fc:igtLabel>
         <fc:igtSyn>saubohne</fc:igtSyn>
         <fc:igtSyn>dicke bohne</fc:igtSyn>
         <fc:igtSyn>großebohne</fc:igtSyn>
         <fc:igtClass>veg</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ackerrettich">
         <fc:igtLabel>Ackerrettich</fc:igtLabel>
         <fc:igtSyn>acker-rettich</fc:igtSyn>
         <fc:igtSyn>hederich</fc:igtSyn>
         <fc:igtSyn>häderich</fc:igtSyn>
         <fc:igtClass>veg</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="agavendicksaft">
         <fc:igtLabel>Agavendicksaft</fc:igtLabel>
         <fc:igtClass>sweet</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ahornsirup">
         <fc:igtLabel>Ahornsirup</fc:igtLabel>
         <fc:igtClass>sweet</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ajvar">
         <fc:igtLabel>Ajvar</fc:igtLabel>
         <fc:igtSyn>ajwar</fc:igtSyn>
         <fc:igtClass>condi</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="algen">
         <fc:igtLabel>Algen</fc:igtLabel>
         <fc:igtClass>veg</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="amarant">
         <fc:igtLabel>Amarant</fc:igtLabel>
         <fc:igtClass>carb</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="amaretti">
         <fc:igtLabel>Amaretti</fc:igtLabel>
         <fc:igtSyn>amarettini</fc:igtSyn>
         <fc:igtClass>sweet</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="amaretto">
         <fc:igtLabel>Amaretto</fc:igtLabel>
         <fc:igtClass>alc</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ananas">
         <fc:igtLabel>Ananas</fc:igtLabel>
         <fc:igtClass>fruit</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ananassaft">
         <fc:igtLabel>Ananassaft</fc:igtLabel>
         <fc:igtClass>fruit</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="ancho" repl="chili">
         <fc:igtLabel>Ancho</fc:igtLabel>
         <fc:igtSyn>ancho-chilischote</fc:igtSyn>
         <fc:igtClass>spice</fc:igtClass>
      </fc:ingredient>
      <fc:ingredient id="anis">
         <fc:igtLabel>Anis</fc:igtLabel>
